name: bwu_polymer_routing_examples
version: 0.1.2
author: Günter Zöchbauer <guenter@gzoechbauer.com>
description: Examples for the bwu_polymer_routing package
homepage: https://github.com/bwu-dart/bwu_polymer_routing
environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  bwu_polymer_routing:
    path: ..
  di: '>=3.3.2 <5.0.0'
  polymer: ^1.0.0-rc.3
  reflectable: 0.3.3
  route_hierarchical: '>=0.4.21 <0.7.0'
  web_components: ^0.12.0

dev_dependencies:
  bwu_grinder_tasks: '>=0.1.0 <0.2.0'
  grinder: '>=0.7.2 <0.9.0'
  polymer_elements: ^1.0.0-rc.3
  test: '>=0.12.2 <0.13.0'

transformers:
- web_components:
    entry_points:
    - web/example_01.html
    - web/example_02.html
    - web/example_03.html

- reflectable:
    entry_points:
    - web/example_01.dart
    - web/example_02.dart
    - web/example_03.dart

- di

- test/pub_serve:
    $include: test/**_test{.*,}.dart

- $dart2js:
    minify: true
    $include: '**/*.bootstrap.initialize.dart'
    #$include: "**/*.polymer.bootstrap.dart"


