name: bwu_polymer_routing_examples
version: 0.1.2
author: Günter Zöchbauer <guenter@gzoechbauer.com>
description: Examples for the bwu_polymer_routing package
homepage: https://github.com/bwu-dart/bwu_polymer_routing
environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
#  analyzer: ^0.25.0
  di: '>=3.3.2 <5.0.0'
  polymer: '>=0.12.0+7 <0.17.0'
  route_hierarchical: '>=0.4.21 <0.7.0'
  bwu_polymer_routing:
    path: ..

dev_dependencies:
  bwu_grinder_tasks: '>=0.1.0 <0.2.0'
  core_elements: '>=0.1.1+2 <0.8.0'
  grinder: '>=0.7.2 <0.8.0'
  paper_elements: '>=0.1.0+2 <0.8.0'
  test: '>=0.12.2 <0.13.0'

transformers:
- polymer:
    entry_points:
    - web/example_01.html
    - web/example_02.html
    - web/example_03.html

- di

- test/pub_serve:
    $include: test/**_test{.*,}.dart

